# Generated by Django 6.0.3 on 2026-03-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start', models.CharField(max_length=120)),
                ('end', models.CharField(max_length=120)),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
            ],
            options={
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('routes', models.ManyToManyField(related_name='stops', through='routes.RouteStop', to='routes.route')),
            ],
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.stop'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop')},
        ),
    ]
