# Generated by Django 6.0.3 on 2026-03-16 21:00

import django.db.models.deletion
import routes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxiRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('polyline', models.TextField(help_text='JSON list of [lat, lng] points', validators=[routes.models.validate_json_polyline])),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_routes_to', to='routes.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_routes_from', to='routes.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('end_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_paths_end', to='routes.location')),
                ('start_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_paths_start', to='routes.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('taxi', 'Taxi'), ('walk', 'Walk')], max_length=10)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_from_steps', to='routes.location')),
                ('taxi_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.taxiroute')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_to_steps', to='routes.location')),
                ('travel_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='routes.travelpath')),
            ],
            options={
                'ordering': ['travel_path', 'order'],
            },
        ),
    ]
